# noinspection
#@PydevCodeAnalysisIgnore
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\UI\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 605)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 541, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 521, 203))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.qte_pet = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_pet.setText(_fromUtf8(""))
        self.qte_pet.setObjectName(_fromUtf8("qte_pet"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.qte_pet)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.qte_kero = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_kero.setObjectName(_fromUtf8("qte_kero"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.qte_kero)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.qte_diesel = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_diesel.setObjectName(_fromUtf8("qte_diesel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.qte_diesel)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.qte_muni = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_muni.setObjectName(_fromUtf8("qte_muni"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.qte_muni)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.qte_money = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_money.setObjectName(_fromUtf8("qte_money"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.qte_money)
        self.qte_gold = QtGui.QLineEdit(self.formLayoutWidget)
        self.qte_gold.setObjectName(_fromUtf8("qte_gold"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.qte_gold)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.qte_diams = QtGui.QSpinBox(self.formLayoutWidget)
        self.qte_diams.setMinimum(1)
        self.qte_diams.setObjectName(_fromUtf8("qte_diams"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.qte_diams)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 20, 201, 231))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 160, 171))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.min_diams = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.min_diams.setMinimum(1)
        self.min_diams.setMaximum(999)
        self.min_diams.setObjectName(_fromUtf8("min_diams"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.min_diams)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.max_diams = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.max_diams.setMinimum(1)
        self.max_diams.setMaximum(999)
        self.max_diams.setSingleStep(1)
        self.max_diams.setProperty("value", 10)
        self.max_diams.setObjectName(_fromUtf8("max_diams"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.max_diams)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.event_factor = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.event_factor.setMinimum(1)
        self.event_factor.setMaximum(7)
        self.event_factor.setProperty("value", 7)
        self.event_factor.setObjectName(_fromUtf8("event_factor"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.event_factor)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.ratio_factor = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.ratio_factor.setMinimum(1.0)
        self.ratio_factor.setMaximum(6.0)
        self.ratio_factor.setSingleStep(0.01)
        self.ratio_factor.setProperty("value", 6.0)
        self.ratio_factor.setObjectName(_fromUtf8("ratio_factor"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.ratio_factor)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_13)
        self.trade_ratio = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.trade_ratio.setMinimum(0.8)
        self.trade_ratio.setMaximum(1.2)
        self.trade_ratio.setSingleStep(0.01)
        self.trade_ratio.setProperty("value", 0.95)
        self.trade_ratio.setObjectName(_fromUtf8("trade_ratio"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.trade_ratio)
        self.HB_ratio = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.HB_ratio.setMaximum(0.99)
        self.HB_ratio.setSingleStep(0.01)
        self.HB_ratio.setProperty("value", 0.99)
        self.HB_ratio.setObjectName(_fromUtf8("HB_ratio"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.HB_ratio)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 260, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 290, 741, 261))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 721, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.out_account_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.out_account_value.setText(_fromUtf8(""))
        self.out_account_value.setObjectName(_fromUtf8("out_account_value"))
        self.horizontalLayout.addWidget(self.out_account_value)
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 60, 162, 61))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.comboBox_setup = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_setup.setObjectName(_fromUtf8("comboBox_setup"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_setup)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.comboBox_event = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_event.setObjectName(_fromUtf8("comboBox_event"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_event)
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 721, 111))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.out_kero = QtGui.QLabel(self.formLayoutWidget_3)
        self.out_kero.setText(_fromUtf8(""))
        self.out_kero.setObjectName(_fromUtf8("out_kero"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.out_kero)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_21)
        self.out_money = QtGui.QLabel(self.formLayoutWidget_3)
        self.out_money.setText(_fromUtf8(""))
        self.out_money.setObjectName(_fromUtf8("out_money"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.out_money)
        self.out_diams = QtGui.QLabel(self.formLayoutWidget_3)
        self.out_diams.setText(_fromUtf8(""))
        self.out_diams.setObjectName(_fromUtf8("out_diams"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.out_diams)
        self.out_acc = QtGui.QLabel(self.formLayoutWidget_3)
        self.out_acc.setText(_fromUtf8(""))
        self.out_acc.setObjectName(_fromUtf8("out_acc"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.out_acc)
        self.out_gain = QtGui.QLabel(self.formLayoutWidget_3)
        self.out_gain.setText(_fromUtf8(""))
        self.out_gain.setObjectName(_fromUtf8("out_gain"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.out_gain)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(290, 260, 151, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 260, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout_Me = QtGui.QAction(MainWindow)
        self.actionAbout_Me.setObjectName(_fromUtf8("actionAbout_Me"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionImport_2 = QtGui.QAction(MainWindow)
        self.actionImport_2.setObjectName(_fromUtf8("actionImport_2"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAbout_Me)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Valeur de compte", None))
        self.label.setText(_translate("MainWindow", "Pet", None))
        self.label_2.setText(_translate("MainWindow", "kero", None))
        self.label_3.setText(_translate("MainWindow", "Diesel", None))
        self.label_4.setText(_translate("MainWindow", "Muni", None))
        self.label_5.setText(_translate("MainWindow", "Money", None))
        self.label_6.setText(_translate("MainWindow", "Or", None))
        self.label_10.setText(_translate("MainWindow", "Nb de Diams", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Setting", None))
        self.label_7.setText(_translate("MainWindow", "Min diams par event", None))
        self.label_8.setText(_translate("MainWindow", "Max diams par event", None))
        self.label_9.setText(_translate("MainWindow", "Event x", None))
        self.label_11.setText(_translate("MainWindow", "Ratio pts", None))
        self.label_12.setText(_translate("MainWindow", "Taux Commerce", None))
        self.label_13.setText(_translate("MainWindow", "% de HB utilisé", None))
        self.pushButton.setText(_translate("MainWindow", "Calcul", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Resultat", None))
        self.label_14.setText(_translate("MainWindow", "Valeur de compte Actuelle :", None))
        self.label_15.setText(_translate("MainWindow", "Diams par event :", None))
        self.label_16.setText(_translate("MainWindow", "Event n° :", None))
        self.label_17.setText(_translate("MainWindow", "Kerosène :", None))
        self.label_18.setText(_translate("MainWindow", "Money :", None))
        self.label_19.setText(_translate("MainWindow", "Diams restants :", None))
        self.label_20.setText(_translate("MainWindow", "Valeur de compte :", None))
        self.label_21.setText(_translate("MainWindow", "Gain par diamant :", None))
        self.pushButton_2.setText(_translate("MainWindow", "Graph", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAbout_Me.setText(_translate("MainWindow", "About Me", None))
        self.actionAbout_Me.setShortcut(_translate("MainWindow", "Ctrl+F1", None))
        self.actionImport.setText(_translate("MainWindow", "Import ...", None))
        self.actionImport_2.setText(_translate("MainWindow", "Import...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

