# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import gpx_explorer.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx_explorer', '0002_auto_20170602_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx_file',
            name='file',
            field=models.FileField(upload_to=gpx_explorer.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='gpx_file',
            name='key',
            field=models.CharField(default='5uHgn9oar0WX0Erl57NV7sZWqFg6BHdE', max_length=32),
        ),
    ]
