# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'game', 'vote_type')]),
        ),
    ]
