# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
