# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_proj', '0005_video_restricted_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='restricted_to',
        ),
    ]
