# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_proj', '0011_video_restricted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='restricted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
