# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_proj', '0003_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
