# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_proj', '0007_auto_20170517_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
