# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='gpx_file',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='gpx_file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gpx_file',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
